[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "chromium", "glib", "nss", "nspr", "dbus", "atk", "cups", "libdrm", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXfixes", "xorg.libXrandr", "xorg.libxcb", "libxkbcommon", "pango", "cairo", "alsa-lib"]

[phases.install]
cmds = ["pip3 install -r requirements.txt", "python3 -m playwright install chromium"]

[start]
cmd = "python3 control_bot.py"
